type State = 'online' | 'offline' | 'connecting';
type Service = { id:string; name:string; url:string; enabled:boolean; state:State; lastSeen?:string; latency?:number; socket?:WebSocket };
type Event = { time:string; type:State; service:string; message:string };
const STORAGE = 'pulsewatch.services.v1', SETTINGS = 'pulsewatch.settings.v1';
const demo: Service[] = [
  {id:'demo-core',name:'Core API',url:'https://api.ejemplo.com',enabled:true,state:'connecting'},
  {id:'demo-auth',name:'Servicio de identidad',url:'https://auth.ejemplo.com',enabled:true,state:'connecting'},
  {id:'demo-pay',name:'Pasarela de pagos',url:'https://payments.ejemplo.com',enabled:false,state:'offline'},
];
let services:Service[] = [], events:Event[] = [], page=1, activeView='dashboard', filter='all', query='';
let settings={ reconnect:5000 };
const $ = <T extends HTMLElement>(selector:string) => document.querySelector(selector) as T;
const statusText:Record<State,string>={online:'OPERATIVO',offline:'SIN CONEXIÓN',connecting:'CONECTANDO'};
async function load(){ try{const response=await fetch('/api/services');if(!response.ok)throw new Error();services=(await response.json()).services;}catch{try{services=JSON.parse(localStorage.getItem(STORAGE)||'null')||demo;}catch{services=demo}}try{settings={...settings,...JSON.parse(localStorage.getItem(SETTINGS)||'{}')};}catch{}}
async function refreshServices(){try{const response=await fetch('/api/services',{cache:'no-store'});if(!response.ok)return;const next=(await response.json()).services as Service[];const before=JSON.stringify(services.map(({socket,...service})=>service));const after=JSON.stringify(next);if(before!==after){services=next;render();}}catch{/* El monitor sigue mostrando el último estado conocido. */}}
let liveSocket: WebSocket | undefined;
function applyLiveUpdate(payload: { scope?:string; services?:Service[]; service?:Service }){if(payload.scope==='all'&&Array.isArray(payload.services)){const before=JSON.stringify(services.map(({socket,...service})=>service));const after=JSON.stringify(payload.services);if(before!==after){services=payload.services;render();}return}if(payload.scope==='service'&&payload.service){const index=services.findIndex(service=>service.id===payload.service!.id);if(index>=0){services[index]={...services[index],...payload.service};render();}}}
function connectToMonitor(){liveSocket?.close();const protocol=location.protocol==='https:'?'wss:':'ws:';liveSocket=new WebSocket(`${protocol}//${location.host}/ws`);liveSocket.onopen=()=>{$('#monitorState').textContent='Monitor activo';};liveSocket.onmessage=(event)=>{try{const payload=JSON.parse(event.data);if(payload.type==='snapshot'||payload.type==='status')applyLiveUpdate(payload);}catch{/* Se ignoran mensajes externos no válidos. */}};liveSocket.onclose=()=>{$('#monitorState').textContent='Reconectando panel…';window.setTimeout(connectToMonitor,3000);};liveSocket.onerror=()=>liveSocket?.close();}
function persist(){localStorage.setItem(STORAGE,JSON.stringify(services.map(({socket,...s})=>s)))}
function socketUrl(raw:string){const url=new URL(raw.startsWith('ws')?raw:`https://${raw.replace(/^https?:\/\//,'')}`);url.protocol=url.protocol==='https:'||url.protocol==='wss:'?'wss:':'ws:';url.pathname=`${url.pathname.replace(/\/$/,'')}/status`;return url.toString()}
function log(type:State,service:string,message:string){events.unshift({time:new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit',second:'2-digit'}),type,service,message});events=events.slice(0,100);renderActivity()}
function connect(service:Service){ if(!service.enabled)return; service.socket?.close(); service.state='connecting';render(); let started=performance.now();try{const socket=new WebSocket(socketUrl(service.url));service.socket=socket;socket.onopen=()=>{service.state='online';service.lastSeen=new Date().toISOString();service.latency=Math.round(performance.now()-started);log('online',service.name,'WebSocket conectado');persist();render()};socket.onmessage=()=>{service.lastSeen=new Date().toISOString();if(service.state!=='online'){service.state='online';render()}};socket.onerror=()=>socket.close();socket.onclose=()=>{if(service.socket!==socket)return;const wasOnline=service.state==='online';service.state='offline';if(wasOnline)log('offline',service.name,'Conexión WebSocket cerrada');render();window.setTimeout(()=>{if(service.enabled&&service.state==='offline')connect(service)},settings.reconnect)}}catch{service.state='offline';render()} }
function statusRow(s:Service){return `<div class="status-row"><i class="dot ${s.state}"></i><div><div class="status-name">${escape(s.name)}</div></div><div class="status-url">${escape(socketUrl(s.url))}</div><div class="status-meta">${s.latency?`${s.latency} ms`:'—'}</div><span class="state ${s.state}">${statusText[s.state]}</span><button class="row-menu" data-edit="${s.id}">•••</button></div>`}
function render(){const active=services.filter(s=>s.enabled), online=active.filter(s=>s.state==='online');$('#serviceCount').textContent=String(services.length);$('#activeTotal').textContent=`${online.length}/${active.length}`;$('#activeDetail').textContent=active.length?`${online.length} operativos ahora`:'No hay monitores activos';$('#incidentTotal').textContent=String(active.filter(s=>s.state==='offline').length);$('#uptimeTotal').textContent=active.length?`${Math.round((online.length/active.length)*100)}%`:'—';$('#lastUpdate').textContent=`Actualizado ${new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'})}`;const featured=services.slice(0,5);$('#statusList').innerHTML=featured.length?featured.map(statusRow).join(''):'<div class="empty">Aún no has añadido servicios.</div>';$('#dashboardPagination').textContent=services.length>5?`Mostrando 5 de ${services.length} servicios`:`${services.length} servicios`;renderServices()}
function renderServices(){const result=services.filter(s=>(filter==='all'||s.state===filter)&&(s.name+s.url).toLowerCase().includes(query.toLowerCase()));const total=Math.max(1,Math.ceil(result.length/8));page=Math.min(page,total);const current=result.slice((page-1)*8,page*8);$('#servicesTable').innerHTML=`<div class="table-head"><span>SERVICIO</span><span>ENDPOINT WEBSOCKET</span><span>ESTADO</span><span>ÚLTIMA SEÑAL</span><span></span></div>${current.length?current.map(s=>`<div class="service-row"><div><strong>${escape(s.name)}</strong><div class="status-url">${escape(s.url)}</div></div><div class="status-url">${escape(socketUrl(s.url))}</div><span class="state ${s.state}">${statusText[s.state]}</span><span class="status-meta">${s.lastSeen?new Date(s.lastSeen).toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'}):'Sin señal'}</span><div class="actions"><button class="icon-button" title="Reconectar" data-reconnect="${s.id}">↻</button><button class="icon-button" title="Editar" data-edit="${s.id}">✎</button><button class="icon-button" title="Eliminar" data-delete="${s.id}">×</button></div></div>`).join(''):'<div class="empty">No hay servicios que coincidan.</div>'}`;$('#pageInfo').textContent=`Página ${page} de ${total}`;($('#prevPage') as HTMLButtonElement).disabled=page===1;($('#nextPage') as HTMLButtonElement).disabled=page===total}
function renderActivity(){$('#activityList').innerHTML=events.length?events.map(e=>`<div class="activity-row"><time>${e.time}</time><i class="dot ${e.type}"></i><span><b>${escape(e.service)}</b> · ${e.message}</span><span class="state ${e.type}">${statusText[e.type]}</span></div>`).join(''):'<div class="empty">Todavía no hay eventos en esta sesión.</div>'}
function escape(value:string){const el=document.createElement('span');el.textContent=value;return el.innerHTML}
function openForm(service?:Service){const dialog=$<HTMLDialogElement>('#serviceDialog');$('#serviceId').value=service?.id||'';$('#serviceName').value=service?.name||'';$('#serviceUrl').value=service?.url||'';($('#serviceEnabled') as HTMLInputElement).checked=service?.enabled??true;$('#formTitle').textContent=service?'Editar servicio':'Añadir servicio';$('#formKicker').textContent=service?'CONFIGURACIÓN':'NUEVO ENDPOINT';dialog.showModal()}
function go(view:string){activeView=view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}View`));document.querySelectorAll('.nav-link[data-view]').forEach(v=>v.classList.toggle('active',(v as HTMLElement).dataset.view===view));const names:Record<string,[string,string]>={dashboard:['Vista general','MONITORIZACIÓN EN DIRECTO'],services:['Servicios','GESTIÓN DE ENDPOINTS'],activity:['Actividad','EVENTOS DE ESTA SESIÓN']};$('#viewTitle').textContent=names[view][0];$('#viewKicker').textContent=names[view][1]}
void load().then(()=>{render();renderActivity();connectToMonitor();});
$('#addService').onclick=()=>openForm();document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go((b as HTMLElement).dataset.go!)));document.querySelectorAll('.nav-link[data-view]').forEach(b=>b.addEventListener('click',()=>go((b as HTMLElement).dataset.view!)));
document.querySelectorAll<HTMLElement>('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>button.closest('dialog')?.close()));
document.addEventListener('click',(e)=>{const t=e.target as HTMLElement;const id=t.closest<HTMLElement>('[data-edit],[data-delete],[data-reconnect]')?.dataset;if(!id)return;const s=services.find(x=>x.id===id.edit||x.id===id.delete||x.id===id.reconnect);if(!s)return;if(id.edit)openForm(s);if(id.delete&&confirm(`¿Eliminar ${s.name}?`)){void fetch(`/api/services/${s.id}`,{method:'DELETE'});s.socket?.close();services=services.filter(x=>x!==s);persist();log('offline',s.name,'Servicio eliminado');render()}if(id.reconnect){void refreshServices();log('connecting',s.name,'Actualización de estado solicitada')}});
$('#serviceForm').addEventListener('submit',async(e)=>{e.preventDefault();const id=$('#serviceId').value;const name=$('#serviceName').value.trim(),url=$('#serviceUrl').value.trim(),enabled=($('#serviceEnabled') as HTMLInputElement).checked;try{socketUrl(url)}catch{alert('Introduce una URL válida.');return}const response=await fetch(id?`/api/services/${id}`:'/api/services',{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,url,enabled})});if(!response.ok){alert('No se ha podido guardar el servicio.');return}const saved=await response.json() as Service;let s=services.find(x=>x.id===id);if(s){Object.assign(s,saved);log('connecting',s.name,'Configuración actualizada')}else{s=saved;services.unshift(s);log('connecting',s.name,'Servicio añadido')}persist();$('#serviceDialog').close();render();void refreshServices()});
$('#searchInput').addEventListener('input',e=>{query=(e.target as HTMLInputElement).value;page=1;renderServices()});$('#statusFilter').addEventListener('change',e=>{filter=(e.target as HTMLSelectElement).value;page=1;renderServices()});$('#prevPage').onclick=()=>{page--;renderServices()};$('#nextPage').onclick=()=>{page++;renderServices()};$('#refreshAll').onclick=()=>void refreshServices();$('#clearActivity').onclick=()=>{events=[];renderActivity()};$('#openSettings').onclick=()=>{($('#reconnectInterval') as HTMLSelectElement).value=String(settings.reconnect);$<HTMLDialogElement>('#settingsDialog').showModal()};$('#saveSettings').onclick=()=>{settings.reconnect=Number(($('#reconnectInterval') as HTMLSelectElement).value);localStorage.setItem(SETTINGS,JSON.stringify(settings))};setInterval(()=>{$('#clock').textContent=new Date().toLocaleTimeString('es-ES',{hour:'2-digit',minute:'2-digit'});},1000);
